### ISSUE TITLE
Question: Reject topic subscription based on user rights

### ISSUE THREAD

**Issue by tomikiss** [rstoyanchev/spring-websocket-portfolio#23]
What would you suggest how we could implement an interceptor on the server side which can filter the client topic subscription and reject subscription for user which doesn't allowed on a topic.

For example:
In the stock example project we have Quote for 3 instrument: Apple, Microsoft, Google
And have two user: User1, User2

User1 should have access to Apple and Microsoft
User2 should have access to Google only

If User1 subscribe to Google should get rejected, and message shouldn't broadcast to him.

**Comment by hartz89** [comment]
Is it possible to achieve this permissions-checking behavior using the `@SubscripeMapping` annotation provided by Spring Messaging 4.X?  I ask because I am trying to set up numerous topics which may require different permissions logic.  Using the interceptor method is unwieldy in this case because I would need to inspect the topic name to determine which permissions logic should be used.
